/* export_timeline.js — the narration clock, cuts, seams and shots for build/QA tools.
     node export_timeline.js scenes/timing_film_data.js scenes/shots.js  → out/timeline.json
   cuts  = FILM.openEnd, FILM.close and every shot start that is not a `seam` hand-off, plus every ledger cut
   seams = seams.json (if present) resolved on the clock and validated (axis/direction/ping-pong); also written as
           scenes/seams_data.js so the scene can load the ledger without fetch (deterministic contract)
   shots = {clip, t0, t1, establish} per shot (gates: ui colour truth, motion diagnostics)
   sync  = named sync points a scene publishes via window.__sync (blocks → SFX cues) */
const path = require('path'), fs = require('fs');
const [timing, shots] = process.argv.slice(2);
if (!timing || !shots) { console.error('usage: node export_timeline.js <timing_data.js> <shots.js>'); process.exit(2); }
global.window = global;
const here = path.dirname(process.argv[1]);
const lib = f => path.resolve(here, 'scenes/lib', f);
require(lib('grammar.js'));
global.TX = require(lib('timeline.js')).load(timing);
require(lib('footage.js'));
if (fs.existsSync(lib('camera.js'))) require(lib('camera.js'));
require(path.resolve(shots));
const F = global.FILM || {}, SH = global.SHOTS || [];
const uniq = a => a.map(x => +x.toFixed(3)).filter((v, i, arr) => arr.indexOf(v) === i).sort((a, b) => a - b);

let cuts = [F.openEnd, F.close].concat(SH.filter(s => !s.seam).map(s => s.t0)).filter(x => typeof x === 'number');

let seams = [], current;
const seamsPath = path.resolve(here, 'seams.json');
if (fs.existsSync(seamsPath) && fs.existsSync(lib('seams.js'))) {
  const SEAM = require(lib('seams.js'));
  const ledger = JSON.parse(fs.readFileSync(seamsPath, 'utf8'));
  SEAM.build(ledger, global.TX, F);
  const v = SEAM.validate(SEAM.ledger().rows);
  v.warnings.forEach(w => console.log('WARN seams: ' + w));
  if (!v.ok) { console.error('seams.json: ' + v.errors.join('\n  ')); process.exit(1); }
  seams = SEAM.toJSON().seams; current = SEAM.ledger().current;
  cuts = cuts.concat(seams.map(s => s.cut));
  fs.writeFileSync(path.resolve(here, 'scenes/seams_data.js'), '/* generated by export_timeline.js from seams.json -- do not edit */\nwindow.SEAMS_LEDGER = ' + JSON.stringify(ledger) + ';\n');
} else if (!fs.existsSync(path.resolve(here, 'scenes/seams_data.js'))) {
  fs.writeFileSync(path.resolve(here, 'scenes/seams_data.js'), '/* no seams.json in this project */\n');
}
cuts = uniq(cuts);

const shotList = SH.map(s => ({ clip: s.clip, t0: +s.t0.toFixed(3), t1: s.t1 === undefined ? null : +s.t1.toFixed(3), establish: s.establish || null, seam: !!s.seam }));
const sync = (global.__sync || []).map(s => ({ id: s.id, t: +s.t.toFixed(3) }));

fs.mkdirSync(path.resolve(here, 'out'), { recursive: true });
const out = { total: TX.total, cuts, seams, current, shots: shotList, sync, phases: TX.PHASES.phases };
fs.writeFileSync(path.resolve(here, 'out/timeline.json'), JSON.stringify(out, null, 1));
console.log('total ' + TX.total.toFixed(2) + ' s | ' + cuts.length + ' cuts | ' + seams.length + ' seams | ' + shotList.length + ' shots -> out/timeline.json');
