/* export_timeline.js — the narration clock, cuts, seams and shots for build/QA tools.
     node export_timeline.js scenes/timing_film_data.js scenes/shots.js  → out/timeline.json
   cuts  = FILM.openEnd, FILM.close and every shot start that is not a `seam` hand-off, plus every ledger cut
   seams = seams.json (if present) resolved on the clock and validated (axis/direction/ping-pong); also written as
           scenes/seams_data.js so the scene can load the ledger without fetch (deterministic contract)
   shots = {clip, t0, t1, establish} per shot (gates: ui colour truth, motion diagnostics)
   sync  = named sync points a scene publishes via window.__sync (blocks → SFX cues)
   reveals = reveals.json (optional) planned through lib/reveals.js, so reveal_gate needs no Chrome
   ledgers = anything shots.js or a lib registered under global.__ledgers {reveals, annot, glass, light} rides along
   scene data twins (a file: page cannot fetch): scenes/claims_data.js (window.CLAIMS from claims.json) and
   scenes/events_data.js (window.EVENTS from events.jsonl, meta line first) — both generated, both git-ignored */
const path = require('path'), fs = require('fs');
const [timing, shots] = process.argv.slice(2);
if (!timing || !shots) { console.error('usage: node export_timeline.js <timing_data.js> <shots.js>'); process.exit(2); }
global.window = global;
const here = path.dirname(process.argv[1]);
const lib = f => path.resolve(here, 'scenes/lib', f);
require(lib('grammar.js'));
global.TX = require(lib('timeline.js')).load(timing);
require(lib('footage.js'));
if (fs.existsSync(lib('camera.js'))) require(lib('camera.js'));
require(path.resolve(shots));
const F = global.FILM || {}, SH = global.SHOTS || [];
const uniq = a => a.map(x => +x.toFixed(3)).filter((v, i, arr) => arr.indexOf(v) === i).sort((a, b) => a - b);

let cuts = [F.openEnd, F.close].concat(SH.filter(s => !s.seam).map(s => s.t0)).filter(x => typeof x === 'number');

let seams = [], current, glSeams = [];
const seamsPath = path.resolve(here, 'seams.json');
if (fs.existsSync(seamsPath) && fs.existsSync(lib('seams.js'))) {
  const SEAM = require(lib('seams.js'));
  const ledger = JSON.parse(fs.readFileSync(seamsPath, 'utf8'));
  SEAM.build(ledger, global.TX, F);
  const v = SEAM.validate(SEAM.ledger().rows);
  v.warnings.forEach(w => console.log('WARN seams: ' + w));
  if (!v.ok) { console.error('seams.json: ' + v.errors.join('\n  ')); process.exit(1); }
  seams = SEAM.toJSON().seams; current = SEAM.ledger().current;
  glSeams = SEAM.glSeams();                                   // shader seams: {id, at, dur, name, cause} for GL.cutTransition + the gates
  cuts = cuts.concat(seams.map(s => s.cut));
  fs.writeFileSync(path.resolve(here, 'scenes/seams_data.js'), '/* generated by export_timeline.js from seams.json -- do not edit */\nwindow.SEAMS_LEDGER = ' + JSON.stringify(ledger) + ';\n');
} else if (!fs.existsSync(path.resolve(here, 'scenes/seams_data.js'))) {
  fs.writeFileSync(path.resolve(here, 'scenes/seams_data.js'), '/* no seams.json in this project */\n');
}
cuts = uniq(cuts);

// reveals.json (optional): rows {id, kind, at | land (seconds or a cue expression like P.nb / wt('nb','counts')), dur?, target?, particles?, seed?, clip}
let reveals = [];
const revPath = path.resolve(here, 'reveals.json');
if (fs.existsSync(revPath) && fs.existsSync(lib('reveals.js'))) {
  const REVEAL = require(lib('reveals.js'));
  const SEAM = fs.existsSync(lib('seams.js')) ? require(lib('seams.js')) : null;
  const doc = JSON.parse(fs.readFileSync(revPath, 'utf8')), rows = Array.isArray(doc) ? doc : (doc.reveals || []);
  const num = v => typeof v === 'number' ? v : (SEAM && SEAM.resolveCut ? SEAM.resolveCut(v, global.TX, F) : +v);   // same cue resolver as seams.json
  reveals = rows.map(r => Object.assign(REVEAL.plan(Object.assign({}, r, r.at !== undefined ? { at: num(r.at) } : {}, r.land !== undefined ? { land: num(r.land) } : {})), { id: r.id, clip: r.clip }));
}

/* scene data twins: a file: page cannot fetch, so claims.json and events.jsonl are written as scripts the scene loads
   after broll/clips.js. events_data.js is as confidential as the recording it was taken from — keep both git-ignored. */
const NL = String.fromCharCode(10);
const claimsPath = path.resolve(here, 'claims.json');
fs.writeFileSync(path.resolve(here, 'scenes/claims_data.js'), '/* generated by export_timeline.js from claims.json -- do not edit */' + NL +
  'window.CLAIMS = ' + (fs.existsSync(claimsPath) ? JSON.stringify(JSON.parse(fs.readFileSync(claimsPath, 'utf8'))) : '{}') + ';' + NL);
const eventsPath = path.resolve(here, 'events.jsonl');
const events = fs.existsSync(eventsPath) ? fs.readFileSync(eventsPath, 'utf8').split(/\r?\n/).map(l => l.trim()).filter(Boolean).map(l => JSON.parse(l)) : [];
fs.writeFileSync(path.resolve(here, 'scenes/events_data.js'), '/* generated by export_timeline.js from events.jsonl -- do not edit; as confidential as the recording */' + NL +
  'window.EVENTS = ' + JSON.stringify(events) + ';' + NL);

// play{} rides along as plain data (functions such as play.map are dropped) so tools/cutlist.py can round-trip the edit;
// hold = the fraction of the shot after which only the background may move (gates/hold_gate.py)
const playData = p => { if (!p) return null; const o = {}; for (const k of ['at', 'from', 'to', 'rate', 'loop', 'reverse']) if (p[k] !== undefined && typeof p[k] !== 'function') o[k] = p[k]; if (p.map) o.map = true; return o; };
const shotList = SH.map(s => Object.assign({ clip: s.clip, t0: +s.t0.toFixed(3), t1: s.t1 === undefined ? null : +s.t1.toFixed(3), establish: s.establish || null, seam: !!s.seam },
  s.play ? { play: playData(s.play) } : {}, typeof s.hold === 'number' ? { hold: s.hold } : {},
  s.spec && typeof s.spec === 'object' ? { spec: { forbidden: s.spec.forbidden || [], claims: s.spec.claims || [], references: s.spec.references || [] } } : {}));
// holds: FILM.holds declares the recreated segments' hold windows ({id, t0, t1, hold, bg?}); footage shots add theirs from `hold`
const holds = (F.holds || []).map(h => Object.assign({}, h, { t0: +(+h.t0).toFixed(3), t1: +(+h.t1).toFixed(3) }))
  .concat(SH.filter(s => typeof s.hold === 'number' && s.t1 !== undefined).map(s => ({ id: s.clip, t0: +s.t0.toFixed(3), t1: +s.t1.toFixed(3), hold: s.hold, bg: s.holdBg, footage: true })));
// sync points a scene declares (block landings, stamps, flashes) — kind/act ride along so audio/sfx_place.py can route cues and apply the one-impact-per-act rule
const sync = (global.__sync || []).map(s => Object.assign({ id: s.id, t: +s.t.toFixed(3) }, s.kind ? { kind: s.kind } : {}, s.act ? { act: s.act } : {}));

fs.mkdirSync(path.resolve(here, 'out'), { recursive: true });
const out = { total: TX.total, cuts, seams, glSeams, current, shots: shotList, holds, sync, reveals, phases: TX.PHASES.phases };
// v5 ledgers a lib or shots.js registered while loading under Node (global.__ledgers = {reveals, annot, glass, light}) ride into
// timeline.json so reveal_gate / annotate_gate / the glass and light checks can read them without launching Chrome
const LG = global.__ledgers || {};
for (const k of ['reveals', 'annot', 'glass', 'light']) {
  if (LG[k] === undefined || LG[k] === null) continue;
  if (k === 'reveals' && reveals.length) continue;                        // reveals.json wins when both exist
  out[k] = LG[k];
}
fs.writeFileSync(path.resolve(here, 'out/timeline.json'), JSON.stringify(out, null, 1));
console.log('total ' + TX.total.toFixed(2) + ' s | ' + cuts.length + ' cuts | ' + seams.length + ' seams | ' + shotList.length + ' shots | ' +
  (out.reveals || []).length + ' reveals | ' + events.length + ' events -> out/timeline.json (+ scenes/claims_data.js, scenes/events_data.js)');
