# -*- coding: utf-8 -*-
"""_receipts.py — the receipts a v5 scene publishes at mount, read once and shared by the gates.

A scene built on lib/motion.js mounts every block, reveal, chart and mark at load, before frame 0. Each library
keeps a receipt of what it mounted (REVEAL.list(), ANNOTATE.ledger(), GLASS.ledger(), LIGHT.ledger(),
CHART.manifest(), window.__sync). The gates need those receipts without a DOM of their own, so this module:

  1. reads out/scene_receipts.json when it is newer than the scene and scenes/shots.js (render_frames.js or an
     earlier gate run wrote it);
  2. otherwise opens the scene once in headless Chrome (puppeteer, the same GL + compositor flags as the render),
     awaits __seek(0) (and the middle of every assemble window so pixel sampling has run), evaluates the receipts
     and writes out/scene_receipts.json;
  3. caches the result on ctx['_receipts'] so one QA run pays for the page at most once.

Scene contract (optional): `window.__receipts = () => ({...})` wins over the per-library globals; the loader fills
any key it does not return. Keys: reveals, annot, glass, light, charts, sync, fps, total, libs (script srcs).

    load(ctx) -> (receipts | None, note)       uses(ctx, 'reveals') -> True when the scene loads lib/reveals.js
    python gates/_receipts.py scenes/film.html  [--out out/scene_receipts.json]   (prints the receipts)
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FILM_DIR = os.path.dirname(HERE)
CHROME_FLAGS = ['--no-sandbox', '--hide-scrollbars', '--font-render-hinting=none', '--disable-lcd-text',
                '--force-color-profile=srgb', '--disable-background-timer-throttling', '--disable-renderer-backgrounding',
                '--disable-background-media-suspend', '--allow-file-access-from-files']

PROBE_JS = r'''/* receipts_probe.js (generated by gates/_receipts.py) — open a frame(t) scene once and print its mount receipts.
   node receipts_probe.js <scene.html> <out.json> */
const puppeteer = require('puppeteer'); const path = require('path'); const fs = require('fs');
function chromePath() {
  if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;
  try { const p = puppeteer.executablePath(); if (fs.existsSync(p)) return p; } catch (e) {}
  return ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
          '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium-browser'].find(fs.existsSync);
}
const [SCENE, OUT] = process.argv.slice(2);
const [sp, sq] = SCENE.split('?');
const URL = 'file://' + path.resolve(sp) + '?' + (sq ? sq + '&' : '') + 'render';
const flags = JSON.parse(process.env.PROBE_FLAGS || '[]');
if (process.env.RENDER_GL !== 'hardware') flags.push('--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--disable-gpu');
const SYNC_FLAGS_WANTED = process.env.RENDER_COMPOSITOR_SYNC !== '0';
/* capture probe (v5.1, shared with render_frames.js): on some Chrome builds the compositor-sync flags make Page.captureScreenshot
   wait forever for a frame that is never drawn. One plain page is screenshotted with a 30 s race; a hang kills that Chrome and
   relaunches without the flags. */
const SYNC_FLAGS = ['--run-all-compositor-stages-before-draw', '--disable-checker-imaging', '--disable-threaded-animation', '--disable-image-animation-resync'];
async function launchWithProbe(mk) {
  let b = await mk(SYNC_FLAGS_WANTED ? SYNC_FLAGS : []), sync = SYNC_FLAGS_WANTED ? 'on' : 'off';
  if (SYNC_FLAGS_WANTED) {
    const probe = async () => { const p = await b.newPage(); await p.setViewport({ width: 320, height: 180, deviceScaleFactor: 1 });
      await p.goto('data:text/html,<body style="margin:0;background:%23082A34"><div style="width:100px;height:50px;background:%23fff"></div></body>');
      await p.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
      await p.screenshot({ type: 'png', clip: { x: 0, y: 0, width: 32, height: 32 } }); await p.close(); return true; };
    const ok = await Promise.race([probe().catch(() => false), new Promise(r => setTimeout(() => r(false), 30000))]);
    if (!ok) { console.error('WARN compositor-sync flags hang Page.captureScreenshot on this Chrome — relaunching without them'); try { b.process() && b.process().kill('SIGKILL'); } catch (e) {} b = await mk([]); sync = 'off (fallback: capture hung with the sync flags)'; }
  }
  return [b, sync];
}
const COLLECT = () => {
  const R = {};
  try { if (typeof window.__receipts === 'function') Object.assign(R, window.__receipts() || {}); } catch (e) { R.receiptsError = String(e && e.message || e); }
  const L = window.__ledgers || {};
  const take = (k, f) => { if (R[k] === undefined) { try { const v = f(); if (v !== undefined) R[k] = v; } catch (e) { R[k + 'Error'] = String(e && e.message || e); } } };
  take('reveals', () => L.reveals || (window.REVEAL && REVEAL.list ? REVEAL.list() : undefined));
  take('annot', () => L.annot || (window.ANNOTATE && ANNOTATE.ledger ? ANNOTATE.ledger() : undefined));
  take('glass', () => L.glass || (window.GLASS && GLASS.ledger ? GLASS.ledger() : undefined));
  take('light', () => L.light || (window.LIGHT && LIGHT.ledger ? LIGHT.ledger() : undefined));
  take('charts', () => window.CHART && CHART.manifest ? CHART.manifest() : undefined);
  take('sync', () => window.__sync);
  take('fps', () => (window.FILM && window.FILM.fps) || 30);
  take('total', () => window.__total);
  R.libs = Array.from(document.querySelectorAll('script[src]')).map(s => s.getAttribute('src'));
  return JSON.parse(JSON.stringify(R));
};
(async () => {
  const errors = [];
  const [b, compositorSync] = await launchWithProbe(sync => puppeteer.launch({ headless: 'new', executablePath: chromePath(), protocolTimeout: 900000,
    args: flags.concat(sync, ['--force-device-scale-factor=1.5', '--window-size=1280,760']) }));
  const p = await b.newPage();
  p.on('pageerror', e => errors.push('PAGEERROR ' + e.message));
  await p.setViewport({ width: 1280, height: 720, deviceScaleFactor: 1.5 });
  await p.goto(URL, { waitUntil: 'load', timeout: 120000 });
  await p.evaluate(() => document.fonts.ready);
  await p.evaluate(() => { document.body.classList.remove('pre'); return window.__seek ? window.__seek(0) : null; });
  let R = await p.evaluate(COLLECT);
  const mids = (R.reveals || []).filter(r => r.kind === 'assemble').map(r => r.at + r.dur / 2);
  for (const t of mids) await p.evaluate(t => window.__seek(t), t);
  if (mids.length) R = await p.evaluate(COLLECT);
  R.errors = errors; R.compositor_sync = compositorSync;
  fs.mkdirSync(path.dirname(path.resolve(OUT)), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(R, null, 1));
  await b.close();
  console.log(JSON.stringify({ out: OUT, keys: Object.keys(R), errors }));
})().catch(e => { console.error(String(e && e.message || e)); process.exit(4); });
'''


def _node_env(project):
    env = dict(os.environ, PROBE_FLAGS=json.dumps(CHROME_FLAGS))
    if 'NODE_PATH' not in env:
        for cand in [os.path.join(project, 'node_modules'), os.path.join(FILM_DIR, 'node_modules'),
                     os.path.join(os.path.dirname(project), 'node_modules')]:
            if os.path.isdir(os.path.join(cand, 'puppeteer')):
                env['NODE_PATH'] = cand
                break
    return env


def uses(ctx, lib):
    """True when the scene loads lib/<lib>.js (classic script or a module import)."""
    scene = ctx.get('scene_html')
    if not scene or not os.path.exists(scene):
        return False
    html = open(scene, encoding='utf-8', errors='replace').read()
    return re.search(r'lib/%s\.js' % re.escape(lib), html) is not None


def _fresh(path, deps):
    if not os.path.exists(path):
        return False
    deps = [d for d in deps if d and os.path.exists(d)]
    return not deps or os.path.getmtime(path) >= max(os.path.getmtime(d) for d in deps)


def load(ctx, force=False, timeout=180):
    """(receipts dict | None, note). Cached on ctx['_receipts'] for the rest of the QA run."""
    if not force and '_receipts' in ctx:
        return ctx['_receipts']
    project = ctx.get('project') or '.'
    scene = ctx.get('scene_html')
    out = os.path.join(project, 'out', 'scene_receipts.json')
    res = (None, 'no scene')
    if scene and os.path.exists(scene):
        deps = [scene, ctx.get('shots_js') or os.path.join(project, 'scenes', 'shots.js')]
        if not force and _fresh(out, deps):
            try:
                res = (json.load(open(out, encoding='utf-8')), 'out/scene_receipts.json (cached)')
            except ValueError as e:
                res = (None, 'out/scene_receipts.json unreadable: %s' % e)
        else:
            os.makedirs(os.path.dirname(out), exist_ok=True)
            js = os.path.join(project, 'out', '.receipts_probe.js')
            if not os.path.exists(js) or open(js, encoding='utf-8').read() != PROBE_JS:
                open(js, 'w', encoding='utf-8').write(PROBE_JS)
            try:
                r = subprocess.run(['node', js, os.path.abspath(scene), out], capture_output=True, text=True,
                                   env=_node_env(project), cwd=project, timeout=timeout)
                if r.returncode == 0 and os.path.exists(out):
                    res = (json.load(open(out, encoding='utf-8')), 'receipts probed from the scene')
                else:
                    res = (None, 'receipts probe failed (%s): %s' % (r.returncode, (r.stderr or r.stdout).strip()[-200:]))
            except (OSError, subprocess.TimeoutExpired) as e:
                res = (None, 'receipts probe unavailable: %s' % type(e).__name__)
    ctx['_receipts'] = res
    return res


def _selftest():
    """A tiny scene that publishes receipts through window.__receipts: probe it, then hit the cache (needs puppeteer)."""
    import tempfile, time
    tmp = tempfile.mkdtemp(prefix='receipts_')
    os.makedirs(os.path.join(tmp, 'scenes'))
    scene = os.path.join(tmp, 'scenes', 'film.html')
    open(scene, 'w', encoding='utf-8').write(
        "<!doctype html><html><head><style>html,body{margin:0;background:#082A34;width:1280px;height:720px}</style></head><body><div id=stage></div>"
        "<script src=\"lib/reveals.js\"></script><script>\nwindow.__sync = [{id: 'kpi:land', t: 2.4}];\n"
        "window.__receipts = () => ({ reveals: [{ kind: 'heroDive', at: 0.1, dur: 0.9, end: 1.0, frame: 30, fps: 30 }], charts: [] });\n"
        "window.__seek = t => Promise.resolve(); window.__step = t => {}; window.__total = 10;\n</script></body></html>")
    ctx = {'project': tmp, 'scene_html': scene, 'shots_js': os.path.join(tmp, 'scenes', 'shots.js')}
    ok = True

    def check(label, cond, detail=''):
        nonlocal ok
        ok = ok and bool(cond)
        print('  %-44s %s  %s' % (label, 'PASS' if cond else 'FAIL', str(detail)[:120]))
    check('uses(): detects lib/reveals.js', uses(ctx, 'reveals') and not uses(ctx, 'charts'))
    t0 = time.time(); R, note = load(ctx); dt = time.time() - t0
    check('probe returns window.__receipts (%.1f s)' % dt, R is not None and R.get('reveals') and R['reveals'][0]['frame'] == 30, note)
    check('globals filled in (sync, total, libs)', R is not None and R.get('sync') == [{'id': 'kpi:land', 't': 2.4}] and R.get('total') == 10 and R.get('libs') == ['lib/reveals.js'], R and R.get('libs'))
    check('no page errors', R is not None and R.get('errors') == [], R and R.get('errors'))
    ctx2 = {'project': tmp, 'scene_html': scene, 'shots_js': ctx['shots_js']}
    R2, note2 = load(ctx2)
    check('second load reads out/scene_receipts.json (cached)', R2 == R and 'cached' in note2, note2)
    check('ctx cache: same object on repeat', load(ctx2)[0] is R2)
    print('\n%s  %s' % ('SELFTEST PASS' if ok else 'SELFTEST FAIL', tmp))
    return 0 if ok else 1


if __name__ == '__main__':
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    if '--selftest' in sys.argv:
        sys.exit(_selftest())
    a = [x for x in sys.argv[1:] if not x.startswith('--')]
    if not a:
        print(__doc__); sys.exit(2)
    scene = os.path.abspath(a[0])
    proj = os.path.dirname(os.path.dirname(scene))
    R, note = load({'scene_html': scene, 'project': proj, 'shots_js': os.path.join(proj, 'scenes', 'shots.js')}, force=True)
    print(note)
    print(json.dumps(R, indent=1)[:4000] if R else 'no receipts')
    sys.exit(0 if R else 1)
