# -*- coding: utf-8 -*-
"""canary.py — determinism canary for frame(t) scenes: the three seek paths must agree.

    python gates/canary.py scenes/film.html [--times 10.7,21.4] [--workers 3] [--fps 30] [--dur 33.2]
                           [--approach 1.0] [--out out/canary] [--cross-machine] [--json] [--selftest]

render_frames.js splits the film across W workers: worker k COLD-seeks to its first frame i0/FPS while worker
k-1 STEPS frame by frame up to i0-1. Any state kept across frames (a cache that only advances, a curtain that
remembers, a seq frame index) shows up as a visible seam exactly at a chunk boundary — the defect booth
reviewers notice and nobody can reproduce. This gate renders a handful of frames three ways and compares the
decoded pixels byte for byte:

  cold #1   new page, __seek(t) once, screenshot                     } equal  -> 'determinism' (run-to-run)
  cold #2   the same again in a fresh page                           }
  stepped   new page, __seek(t - approach), __step every 1/fps to t  -> equal to cold -> 'seek parity'

Default times: every chunk boundary the render will use (round(k*N/W)/fps), the first cut + 0.4 s, 0.5 s
(title card) and END - 0.05 s (tail), capped at qa.json canary.max_times (default 8). Same machine: PASS only
on identical sha256 of the raw pixels. `--cross-machine` relaxes to PSNR >= 40 dB (fonts and Chrome builds drift
across machines unless fonts are localized). On a mismatch a diff PNG (|a-b| x 8) and the changed-pixel % are
written next to the frames. Chrome runs on the software GL path by default, exactly like render_frames.js
(SwiftShader behind ANGLE, GPU process off): WebGL2 is available, frames do not depend on the machine's GPU,
and a DOM screenshot is ~2x faster than through the GPU process. RENDER_GL=hardware opts out of both.

Chrome is launched with the same switches render_frames.js uses (no font hinting, no LCD text, sRGB colour
profile, background throttling off, compositor sync on). The probe mirrors the renderer step for step: every
declared @font-face is loaded explicitly, the cold frame is re-captured until two captures match (first-frame
settle), every __seek/__step decode Promise is awaited, and two animation frames pass between the last step and
the screenshot so the compositor has committed what the step wrote. Every probed time sits exactly on the frame
grid (round(t*fps)/fps, never rounded to milliseconds): the cold seek and the stepped path must land on the same
instant or a gliding glyph reports a seam that is not there.

Public API (gates/snapshot.py reuses the probe):
  probe(scene, times, mode, out_dir, prefix='', approach=1.0, fps=30, dpr=1.5, png=True) -> {t: path}, meta
  frame_hash(path) -> sha256 hex of the decoded RGB bytes
  compare(a, b, diff_png=None) -> {'identical', 'changed_pct', 'psnr'}
  run_canary(scene, times, out_dir, fps=30, approach=1.0, cross_machine=False) -> report dict
  GATE_NAMES = ['determinism', 'seek parity'];  run(ctx)
"""
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile

GATE_NAMES = ['determinism', 'seek parity']
CROSS_MACHINE_PSNR = 40.0            # dB; byte-identical frames report inf
# Same machine: byte-identical, OR invisible — no pixel moved more than the cut threshold AND PSNR >= 60 dB.
# Measured on the Acme sample: Chrome's compositor promotes a fading lower-third to its own layer after a few
# stepped frames, which moved ONE pixel by 21 levels (PSNR 85.8 dB; 68.7 dB with --disable-gpu at the next
# frame). A real seam (per-call state, see selftest) sits near 32 dB with 0.13 % of pixels changed.
SAME_MACHINE_PSNR = 60.0
DIFF_GAIN = 8                        # |a-b| x 8 makes one-level differences visible in the diff PNG
CHANGED_THRESHOLD = 24               # gray levels; the same metric qa_film.py uses for cuts
CHROME_FLAGS = ['--no-sandbox', '--hide-scrollbars', '--font-render-hinting=none', '--disable-lcd-text',
                '--force-color-profile=srgb', '--disable-background-timer-throttling', '--disable-renderer-backgrounding',
                '--disable-background-media-suspend', '--allow-file-access-from-files']

PROBE_JS = r'''/* probe_frames.js (generated by gates/canary.py) — screenshot a frame(t) scene at given times.
   node probe_frames.js <scene.html> <outDir> <times csv> <mode cold|stepped> <approach s> <fps> <dpr> <prefix> <png 1|0> [quality]
   cold: a fresh page per time, __seek(t) once.  stepped: a fresh page per time, __seek(t-approach) then __step each 1/fps up to t.
   Prints one JSON line: {files: {t: path}, chrome, errors: []}. */
const puppeteer = require('puppeteer'); const path = require('path'); const fs = require('fs');
function chromePath() {
  if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;
  try { const p = puppeteer.executablePath(); if (fs.existsSync(p)) return p; } catch (e) {}
  return ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
          '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium-browser'].find(fs.existsSync);
}
const [SCENE, OUT, TIMES, MODE, APPROACH, FPS_S, DPR_S, PREFIX, PNG_S, Q_S] = process.argv.slice(2);
const FPS = parseInt(FPS_S || '30', 10), DPR = parseFloat(DPR_S || '1.5'), PNG = (PNG_S || '1') === '1', Q = parseInt(Q_S || '92', 10);
const [sp, sq] = SCENE.split('?');
const URL = 'file://' + path.resolve(sp) + '?' + (sq ? sq + '&' : '') + 'render';
const flags = JSON.parse(process.env.PROBE_FLAGS || '[]');
// same GL path as render_frames.js: software rasteriser (SwiftShader behind ANGLE) unless RENDER_GL=hardware
if (process.env.RENDER_GL !== 'hardware') flags.push('--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--disable-gpu');
// and the same compositor sync: every raster stage finishes before a frame is drawn (scaled nested layers otherwise differ run to run)
const SYNC_FLAGS_WANTED = process.env.RENDER_COMPOSITOR_SYNC !== '0';
/* capture probe (v5.1, shared with render_frames.js): on some Chrome builds the compositor-sync flags make Page.captureScreenshot
   wait forever for a frame that is never drawn. One plain page is screenshotted with a 30 s race; a hang kills that Chrome and
   relaunches without the flags. */
const SYNC_FLAGS = ['--run-all-compositor-stages-before-draw', '--disable-checker-imaging', '--disable-threaded-animation', '--disable-image-animation-resync'];
async function launchWithProbe(mk) {
  let b = await mk(SYNC_FLAGS_WANTED ? SYNC_FLAGS : []), sync = SYNC_FLAGS_WANTED ? 'on' : 'off';
  if (SYNC_FLAGS_WANTED) {
    const probe = async () => { const p = await b.newPage(); await p.setViewport({ width: 320, height: 180, deviceScaleFactor: 1 });
      await p.goto('data:text/html,<body style="margin:0;background:%23082A34"><div style="width:100px;height:50px;background:%23fff"></div></body>');
      await p.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
      await p.screenshot({ type: 'png', clip: { x: 0, y: 0, width: 32, height: 32 } }); await p.close(); return true; };
    const ok = await Promise.race([probe().catch(() => false), new Promise(r => setTimeout(() => r(false), 30000))]);
    if (!ok) { console.error('WARN compositor-sync flags hang Page.captureScreenshot on this Chrome — relaunching without them'); try { b.process() && b.process().kill('SIGKILL'); } catch (e) {} b = await mk([]); sync = 'off (fallback: capture hung with the sync flags)'; }
  }
  return [b, sync];
}
(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const errors = [], files = {};
  const [b, compositorSync] = await launchWithProbe(sync => puppeteer.launch({ headless: 'new', executablePath: chromePath(), protocolTimeout: 900000,
    args: flags.concat(sync, ['--force-device-scale-factor=' + DPR, '--window-size=1280,760']) }));
  const version = await b.version();
  for (const ts of TIMES.split(',').filter(Boolean)) {
    const t = parseFloat(ts);
    const p = await b.newPage();
    p.on('pageerror', e => errors.push('PAGEERROR t=' + ts + ' ' + e.message));
    p.on('requestfailed', r => { if (!/ERR_ABORTED/.test(r.failure() && r.failure().errorText || '')) errors.push('REQFAILED ' + r.url().slice(-80)); });
    await p.setViewport({ width: 1280, height: 720, deviceScaleFactor: DPR });
    await p.goto(URL, { waitUntil: 'load', timeout: 120000 });
    // mirror render_frames.js: load every declared @font-face explicitly (src:local() faces settle up to ~1 s after fonts.ready)
    await p.evaluate(async () => { await document.fonts.ready; const faces = []; document.fonts.forEach(f => faces.push(f)); await Promise.all(faces.map(f => f.load().catch(() => null))); });
    await new Promise(r => setTimeout(r, 300));
    if (MODE === 'stepped') {
      const i1 = Math.round(t * FPS), i0 = Math.max(0, i1 - Math.round(parseFloat(APPROACH || '1') * FPS));
      await p.evaluate(t => { document.body.classList.remove('pre'); return window.__seek(t); }, i0 / FPS);
      for (let i = i0 + 1; i <= i1; i++) await p.evaluate(t => (window.__step || window.__seek)(t), i / FPS);
    } else {
      // the cold seek lands on the frame-grid instant the stepped path ends on (i1 / FPS), whatever the csv carried
      const tg = Math.round(t * FPS) / FPS;
      await p.evaluate(t => { document.body.classList.remove('pre'); return window.__seek(t); }, tg);
      // and the first-frame settle render_frames.js performs on every worker's cold frame: re-seek and capture until two
      // consecutive captures are byte-identical (max 8 x 250 ms) — a late glyph/image paint is a warm-up, not a seam
      for (let tries = 0, prev = null; tries < 8; tries++) {
        const sig = require('crypto').createHash('md5').update(await p.screenshot({ type: 'png', clip: { x: 0, y: 0, width: 1280, height: 720 } })).digest('hex');
        if (sig === prev) break;
        prev = sig; await new Promise(r => setTimeout(r, 250));
        await p.evaluate(t => window.__seek(t), tg);
        if (tries === 7) errors.push('WARN t=' + ts + ' cold frame did not settle after 8 captures');
      }
    }
    await p.evaluate(() => document.body.offsetHeight);
    // same as render_frames.js: two animation frames so the compositor has committed and activated the last step before the capture
    await p.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    const f = path.join(OUT, PREFIX + ts.replace(/[^0-9.]/g, '_') + (PNG ? '.png' : '.jpg'));
    await p.screenshot(Object.assign({ path: f, type: PNG ? 'png' : 'jpeg', clip: { x: 0, y: 0, width: 1280, height: 720 } }, PNG ? {} : { quality: Q }));
    files[ts] = f.replace(/\\/g, '/');
    await p.close();
  }
  await b.close();
  console.log(JSON.stringify({ files, chrome: version, errors }));
})().catch(e => {
  const msg = String(e && e.message || e);
  if (/3221225595|0xC0000409|STATUS_STACK_BUFFER_OVERRUN/i.test(msg)) console.error('Chrome crashed on launch (STATUS_STACK_BUFFER_OVERRUN): set PUPPETEER_EXECUTABLE_PATH to the system Chrome.');
  console.error(msg); process.exit(4);
});
'''


def _probe_script(project):
    """Write the probe next to the project's out/ so `require('puppeteer')` resolves from the project upward."""
    d = os.path.join(project or os.getcwd(), 'out')
    os.makedirs(d, exist_ok=True)
    p = os.path.join(d, '.probe_frames.js')
    cur = open(p, encoding='utf-8').read() if os.path.exists(p) else None
    if cur != PROBE_JS:
        open(p, 'w', encoding='utf-8').write(PROBE_JS)
    return p


def probe(scene, times, mode, out_dir, prefix='', approach=1.0, fps=30, dpr=1.5, png=True, quality=92, project=None, timeout=600):
    """Screenshot `scene` at `times` (seconds) in `mode` ('cold' | 'stepped'). Returns ({t_str: path}, meta)."""
    scene = os.path.abspath(scene)
    project = project or os.path.dirname(os.path.dirname(scene))
    js = _probe_script(project)
    tcsv = ','.join('%.6f' % t for t in times)      # frame times carry 6 decimals so 1/30 s multiples survive the hand-over
    env = dict(os.environ, PROBE_FLAGS=json.dumps(CHROME_FLAGS))
    r = subprocess.run(['node', js, scene, os.path.abspath(out_dir), tcsv, mode, str(approach), str(fps), str(dpr), prefix,
                        '1' if png else '0', str(quality)], capture_output=True, text=True, env=env, timeout=timeout, cwd=project)
    if r.returncode != 0:
        raise RuntimeError('probe failed (%d): %s' % (r.returncode, (r.stderr or r.stdout).strip()[-400:]))
    meta = json.loads(r.stdout.strip().splitlines()[-1])
    return meta['files'], meta


def frame_hash(path):
    from PIL import Image
    with Image.open(path) as im:
        return hashlib.sha256(im.convert('RGB').tobytes()).hexdigest()


def compare(a, b, diff_png=None):
    """Pixel comparison of two frames: identical flag, changed-pixel % (|gray delta| > 24) and PSNR (dB, inf when equal)."""
    import numpy as np
    from PIL import Image
    A = np.asarray(Image.open(a).convert('RGB'), dtype=np.int16)
    B = np.asarray(Image.open(b).convert('RGB'), dtype=np.int16)
    if A.shape != B.shape:
        return {'identical': False, 'changed_pct': 100.0, 'psnr': 0.0, 'note': 'size differs %s vs %s' % (A.shape, B.shape)}
    d = np.abs(A - B)
    mse = float((d.astype(np.float64) ** 2).mean())
    gray = d.mean(axis=2)
    changed = float((gray > CHANGED_THRESHOLD).mean() * 100.0)
    psnr = float('inf') if mse == 0 else 10.0 * math.log10(255.0 ** 2 / mse)
    identical = bool(mse == 0)
    if diff_png and not identical:
        Image.fromarray(np.clip(d * DIFF_GAIN, 0, 255).astype(np.uint8)).save(diff_png)
    return {'identical': identical, 'changed_pct': round(changed, 3), 'psnr': round(psnr, 2) if psnr != float('inf') else psnr}


def snap(t, fps=30):
    """Exact frame time: the cold probe seeks to this value, the stepped probe ends on round(t*fps)/fps — they must be
    the same instant. Rounding to 3 decimals (7.833 vs frame 235 = 7.8333) moved a gliding title by 0.33 ms and
    reported a 43 dB 'seek parity' failure on a scene whose paths agree to the byte."""
    return round(t * fps) / fps


def default_times(dur, fps=30, workers=3, cuts=(), max_times=8):
    """Chunk boundaries first (the seams), then the first cut + 0.4, the title card at 0.5 and the tail."""
    N = int(round(dur * fps))
    ts = [snap(round(k * N / workers) / fps, fps) for k in range(1, max(1, workers))]
    cuts = sorted(c for c in cuts if 0.5 < c < dur - 0.5)
    if cuts:
        ts.append(snap(cuts[0] + 0.4, fps))
    ts += [snap(0.5, fps), snap(max(0.0, dur - 0.05), fps)]
    out = []
    for t in ts:
        if 0 <= t <= dur and t not in out:
            out.append(t)
    return out[:max_times]


def run_canary(scene, times, out_dir, fps=30, approach=1.0, cross_machine=False, project=None):
    """Three probes, two verdicts. Returns {ok, determinism, parity, chrome, per_time: [...], errors}."""
    os.makedirs(out_dir, exist_ok=True)
    c1, m1 = probe(scene, times, 'cold', out_dir, prefix='cold1_', fps=fps, project=project)
    c2, m2 = probe(scene, times, 'cold', out_dir, prefix='cold2_', fps=fps, project=project)
    st, m3 = probe(scene, times, 'stepped', out_dir, prefix='step_', approach=approach, fps=fps, project=project)
    rows, det_ok, par_ok = [], True, True

    def verdict(a, b, diff_png):
        """(ok, kind, diff) — 'same' (hash), 'near' (invisible raster noise), 'cross' (PSNR >= 40 dB only), 'DIFF'."""
        if frame_hash(a) == frame_hash(b):
            return True, 'same', None
        d = compare(a, b, diff_png)
        if d['changed_pct'] == 0 and d['psnr'] >= SAME_MACHINE_PSNR:
            return True, 'near', d
        if cross_machine and d['psnr'] >= CROSS_MACHINE_PSNR:
            return True, 'cross', d
        return False, 'DIFF', d

    for ts in c1:
        ok1, k1, d1 = verdict(c1[ts], c2[ts], os.path.join(out_dir, 'diff_runs_%s.png' % ts))
        ok2, k2, d2 = verdict(c1[ts], st[ts], os.path.join(out_dir, 'diff_parity_%s.png' % ts))
        row = {'t': float(ts), 'run_to_run': ok1, 'run_to_run_kind': k1, 'parity': ok2, 'parity_kind': k2}
        if d1:
            row['run_to_run_diff'] = d1
        if d2:
            row['parity_diff'] = d2
        det_ok &= ok1; par_ok &= ok2
        rows.append(row)
    errors = m1['errors'] + m2['errors'] + m3['errors']
    return {'ok': det_ok and par_ok and not errors, 'determinism': det_ok, 'parity': par_ok, 'chrome': m1.get('chrome'),
            'times': [float(t) for t in c1], 'per_time': rows, 'errors': errors[:6], 'out': out_dir}


def _detail(rep, key, diffkey):
    bad = [r for r in rep['per_time'] if not r[key]]
    if rep['errors']:
        return 'page errors: ' + rep['errors'][0][:90]
    if not bad:
        near = [r for r in rep['per_time'] if r.get(key + '_kind') in ('near', 'cross')]
        return '%s at %d times (%s)%s' % ('identical' if not near else 'identical/invisible', len(rep['per_time']),
                                          ', '.join('%.2f' % t for t in rep['times'][:6]),
                                          '' if not near else '; raster noise >= %.0f dB at %s' % (SAME_MACHINE_PSNR, ', '.join('%.2f' % r['t'] for r in near[:3])))
    b = bad[0]
    d = b.get(diffkey, {})
    return 'first mismatch t=%.2f: %.2f%% pixels changed, PSNR %s dB -> %s' % (b['t'], d.get('changed_pct', 0), d.get('psnr'), rep['out'])


# ------------------------------------------------------------------------------------------------ QA gate
def run(ctx):
    q = (ctx.get('qa') or {}).get('canary', {}) or {}
    if q.get('enabled', True) is False:
        return [('determinism', True, 'disabled in qa.json'), ('seek parity', True, 'disabled in qa.json')]
    fps = int(ctx.get('fps', 30)); cfg = ctx.get('cfg') or {}
    dur = float(ctx.get('dur') or (ctx.get('timeline') or {}).get('total', 10))
    times = q.get('times') or default_times(dur, fps, int(cfg.get('workers', 3)), (ctx.get('timeline') or {}).get('cuts', []), int(q.get('max_times', 8)))
    out = os.path.join(ctx.get('project') or '.', 'out', 'canary')
    rep = run_canary(ctx['scene_html'], times, out, fps=fps, approach=float(q.get('approach', 1.0)),
                     cross_machine=bool(q.get('cross_machine', False)), project=ctx.get('project'))
    return [('determinism', rep['determinism'] and not rep['errors'], _detail(rep, 'run_to_run', 'run_to_run_diff')),
            ('seek parity', rep['parity'] and not rep['errors'], _detail(rep, 'parity', 'parity_diff'))]


# ------------------------------------------------------------------------------------------------ selftest
_SCENE = '''<!doctype html><html><head><meta charset="utf-8"><style>
html,body{margin:0;background:#082A34;width:1280px;height:720px;overflow:hidden;font-family:Arial,sans-serif}
body.pre #stage{visibility:hidden}
#stage{position:absolute;inset:0;background:linear-gradient(180deg,#082A34,#204A56)}
#box{position:absolute;left:100px;top:200px;width:300px;height:200px;background:#E56B5E;color:#fff;font-size:40px;will-change:transform}
#odo{position:absolute;left:600px;top:300px;color:#E9F3F9;font-size:60px}
</style></head><body><div id="stage"><div id="box">Acme</div><div id="odo"></div></div>
<script>
'use strict';
const RENDER = /[?&]render/.test(location.search);
if (RENDER) document.body.classList.add('pre');
%s
function frame(t) {
  document.getElementById('box').style.transform = 'translate(' + (t * 80).toFixed(2) + 'px,0) rotate(' + (t * 20).toFixed(2) + 'deg)';
  document.getElementById('odo').textContent = value(t);
}
window.__seek = t => { document.body.classList.remove('pre'); frame(t); };
window.__step = t => frame(t);
window.__total = 6;
</script></body></html>'''
GOOD_VALUE = "function value(t) { return Math.round(t * 1000).toLocaleString('en-US'); }"
# the classic seam bug: state that advances per CALL instead of being computed from t (pos += speed each frame)
BAD_VALUE = "let pos = 0; function value(t) { pos += 2; return pos.toLocaleString('en-US'); }"


def selftest():
    d = tempfile.mkdtemp(prefix='canary_selftest_')
    os.makedirs(os.path.join(d, 'scenes'))
    good, bad = os.path.join(d, 'scenes', 'good.html'), os.path.join(d, 'scenes', 'bad.html')
    open(good, 'w', encoding='utf-8').write(_SCENE % GOOD_VALUE)
    open(bad, 'w', encoding='utf-8').write(_SCENE % BAD_VALUE)
    times = default_times(6.0, 30, 3, cuts=[2.0], max_times=3)
    print('selftest  times %s' % times)
    rg = run_canary(good, times, os.path.join(d, 'out', 'good'), project=d)
    print('selftest  good: determinism %s  parity %s  chrome %s' % (rg['determinism'], rg['parity'], rg['chrome']))
    # per-call state: both cold runs draw the same (one call each) so run-to-run passes, but the stepped path has
    # advanced 30 more times when it reaches t — exactly what a worker seam looks like
    rb = run_canary(bad, times, os.path.join(d, 'out', 'bad'), project=d)
    print('selftest  bad : determinism %s  parity %s  (expect True / False)' % (rb['determinism'], rb['parity']))
    ok = rg['ok'] and rb['determinism'] and not rb['parity']
    bad_row = next((r for r in rb['per_time'] if not r['parity']), None)
    if bad_row:
        print('selftest  bad diff: %s' % bad_row.get('parity_diff'))
    shutil.rmtree(d, ignore_errors=True)
    print('selftest  ' + ('PASS' if ok else 'FAIL'))
    return ok


def main(argv):
    if '--selftest' in argv:
        return 0 if selftest() else 1
    args = [a for a in argv if not a.startswith('--')]
    def opt(name, default=None):
        if name in argv and argv.index(name) + 1 < len(argv):
            v = argv[argv.index(name) + 1]
            if v in args:
                args.remove(v)
            return v
        return default
    out = opt('--out', 'out/canary'); fps = int(opt('--fps', 30)); workers = int(opt('--workers', 3))
    dur = opt('--dur'); times = opt('--times'); approach = float(opt('--approach', 1.0))
    if not args:
        print(__doc__.split('\n\n')[0]); return 2
    scene = args[0]
    project = os.path.dirname(os.path.dirname(os.path.abspath(scene)))
    if times:
        times = [snap(float(x), fps) for x in times.split(',') if x.strip()]
    else:
        if not dur:
            tl = os.path.join(project, 'out', 'timeline.json')
            dur = json.load(open(tl))['total'] + 1.2 if os.path.exists(tl) else 10.0
        cuts = []
        tl = os.path.join(project, 'out', 'timeline.json')
        if os.path.exists(tl):
            cuts = json.load(open(tl)).get('cuts', [])
        times = default_times(float(dur), fps, workers, cuts)
    rep = run_canary(scene, times, out, fps=fps, approach=approach, cross_machine='--cross-machine' in argv, project=project)
    if '--json' in argv:
        print(json.dumps(rep, indent=1, default=str))
    else:
        print('canary  chrome %s  %d times: %s' % (rep['chrome'], len(rep['times']), ', '.join('%.2f' % t for t in rep['times'])))
        for r in rep['per_time']:
            print('  t=%6.2f  run-to-run %-5s cold-vs-stepped %-5s %s' % (r['t'], r['run_to_run_kind'], r['parity_kind'],
                  '' if r['parity_kind'] == 'same' else str(r.get('parity_diff'))))
        for e in rep['errors']:
            print('  ' + e)
        print('determinism %s | seek parity %s -> %s' % ('PASS' if rep['determinism'] else 'FAIL', 'PASS' if rep['parity'] else 'FAIL', out))
    return 0 if rep['ok'] else 1


if __name__ == '__main__':
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.exit(main(sys.argv[1:]))
