# -*- coding: utf-8 -*-
"""overflow_gate.py — no text box overflows its own box, at any second of the film.  (qa_film.py plug-in)

A caption that wraps one word past its pill, a kicker whose last letter is clipped, a card line that runs under the
card's edge: nothing in the render reports it, the frame simply shows a cut-off word. This gate opens the scene once in
headless Chrome, seeks it every `step` seconds (default 1 s) and reads every visible element that carries text of its
own: when scrollWidth exceeds clientWidth or scrollHeight exceeds clientHeight by more than 3 px the text does not fit
its box. Excluded on purpose: icon-node labels (an element whose class or `data-overflow-ok` says so — the label is drawn
wider than its node by design), line-height rounding (a vertical excess under half the font size with no horizontal
excess is a descender past a tight line box — a headline at 64 px, a karaoke word span at 22 px — never a lost line, which
is at least one line tall), and full-stage containers (≥ 95 % of the stage in both axes — the stage itself scrolls
nothing a viewer sees).

  text overflow    FAIL with (t, id, text, box, dx, dy) for every offending box; the full list in out/qa/overflow.json

qa.json: {"overflow": {"step": 1.0, "px": 3, "line_frac": 0.5, "ok_classes": ["icon", "node-label"]}}

    python gates/overflow_gate.py scenes/film.html [--total 35.4] [--step 1] [--json]
    python gates/overflow_gate.py --selftest              the judge on synthetic measurements (no browser)
    python gates/overflow_gate.py --selftest --chrome     plus a tiny scene through the real probe
"""
import json, os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
GATE_NAMES = ['text overflow']
DEFAULTS = {'step': 1.0, 'px': 3.0, 'line_frac': 0.5, 'stage_frac': 0.95, 'ok_classes': ['icon', 'node-label', 'label-node'], 'stage': [1280, 720]}
CHROME_FLAGS = ['--no-sandbox', '--hide-scrollbars', '--font-render-hinting=none', '--disable-lcd-text', '--force-color-profile=srgb',
                '--allow-file-access-from-files', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--disable-gpu']

PROBE_JS = r'''/* overflow_probe.js (generated by gates/overflow_gate.py) — seek a frame(t) scene every step and measure every text box.
   node overflow_probe.js <scene.html> <total> <step> <out.json> */
const puppeteer = require('puppeteer'); const path = require('path'); const fs = require('fs');
function chromePath() {
  if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;
  try { const p = puppeteer.executablePath(); if (fs.existsSync(p)) return p; } catch (e) {}
  return ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
          '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium-browser'].find(fs.existsSync);
}
const [SCENE, TOTAL, STEP, OUT] = process.argv.slice(2);
const [sp, sq] = SCENE.split('?');
const URL = 'file://' + path.resolve(sp) + '?' + (sq ? sq + '&' : '') + 'render';
const MEASURE = () => {
  const rows = [], W = innerWidth, H = innerHeight;
  const vis = el => { const cs = getComputedStyle(el); if (cs.display === 'none' || cs.visibility === 'hidden' || parseFloat(cs.opacity) < 0.04) return false;
    let p = el.parentElement; while (p) { const c = getComputedStyle(p); if (c.display === 'none' || c.visibility === 'hidden' || parseFloat(c.opacity) < 0.04) return false; p = p.parentElement; } return true; };
  for (const el of document.body.querySelectorAll('*')) {
    if (!(el instanceof HTMLElement)) continue;
    const own = Array.from(el.childNodes).filter(n => n.nodeType === 3 && n.textContent.trim()).map(n => n.textContent.trim()).join(' ');
    if (!own) continue;
    const r = el.getBoundingClientRect();
    if (r.width < 1 || r.height < 1 || r.right < 0 || r.bottom < 0 || r.left > W || r.top > H) continue;
    if (!vis(el)) continue;
    const cs = getComputedStyle(el);
    rows.push({ id: el.id || '', tag: el.tagName.toLowerCase(), cls: el.className && el.className.baseVal !== undefined ? String(el.className.baseVal) : String(el.className || ''),
      ok: el.hasAttribute('data-overflow-ok'), text: own.slice(0, 60), box: [Math.round(r.left), Math.round(r.top), Math.round(r.width), Math.round(r.height)],
      dx: el.scrollWidth - el.clientWidth, dy: el.scrollHeight - el.clientHeight, font: parseFloat(cs.fontSize) || 0, lh: parseFloat(cs.lineHeight) || 0 });
  }
  return { W, H, rows };
};
(async () => {
  const errors = [];
  const b = await puppeteer.launch({ headless: 'new', executablePath: chromePath(), args: JSON.parse(process.env.PROBE_FLAGS || '[]').concat(['--window-size=1280,760']) });
  const p = await b.newPage();
  p.on('pageerror', e => errors.push('PAGEERROR ' + e.message));
  await p.setViewport({ width: 1280, height: 720, deviceScaleFactor: 1 });
  await p.goto(URL, { waitUntil: 'load', timeout: 120000 });
  await p.evaluate(() => document.fonts.ready);
  await p.evaluate(() => { document.body.classList.remove('pre'); });
  const total = parseFloat(TOTAL), step = parseFloat(STEP), samples = [];
  for (let t = 0; t <= total + 1e-6; t += step) {
    await p.evaluate(t => window.__seek ? window.__seek(t) : null, t);
    await p.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    const m = await p.evaluate(MEASURE);
    samples.push({ t: +t.toFixed(3), W: m.W, H: m.H, rows: m.rows });
  }
  fs.mkdirSync(path.dirname(path.resolve(OUT)), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify({ scene: SCENE, total, step, samples, errors }, null, 1));
  await b.close();
  console.log(JSON.stringify({ out: OUT, samples: samples.length, errors }));
})().catch(e => { console.error(String(e && e.message || e)); process.exit(4); });
'''


def _cfg(qa):
    c = dict(DEFAULTS)
    c.update({k: v for k, v in ((qa or {}).get('overflow') or {}).items()})
    return c


def judge(samples, cfg=None):
    """[(t, id, text, box, dx, dy)] offenders across every sample, after the exclusions."""
    cfg = cfg or DEFAULTS
    out, seen = [], set()
    for s in samples:
        W, H = s.get('W') or cfg['stage'][0], s.get('H') or cfg['stage'][1]
        for r in s.get('rows', []):
            dx, dy = float(r.get('dx') or 0), float(r.get('dy') or 0)
            if dx <= cfg['px'] and dy <= cfg['px']:
                continue
            cls = (r.get('cls') or '').lower()
            if r.get('ok') or any(k in cls for k in cfg['ok_classes']):
                continue                                                   # icon-node labels are wider than their node by design
            box = r.get('box') or [0, 0, 0, 0]
            if box[2] >= cfg['stage_frac'] * W and box[3] >= cfg['stage_frac'] * H:
                continue                                                   # the stage / a full-frame container
            font = float(r.get('font') or 0)
            if dx <= cfg['px'] and font > 0 and dy < cfg['line_frac'] * font:
                continue                                                   # less than half a line of vertical excess is line-height rounding (a descender past a tight line box), never a lost line
            key = (r.get('id') or r.get('text'), round(dx), round(dy))
            if key in seen:
                continue
            seen.add(key)
            out.append((s['t'], r.get('id') or ('<%s>' % r.get('tag', '?')), r.get('text', ''), box, dx, dy))
    return out


def _node_env(project):
    env = dict(os.environ, PROBE_FLAGS=json.dumps(CHROME_FLAGS))
    if 'NODE_PATH' not in env:
        for cand in [os.path.join(project, 'node_modules'), os.path.join(os.path.dirname(HERE), 'node_modules'), os.path.join(os.path.dirname(project), 'node_modules')]:
            if os.path.isdir(os.path.join(cand, 'puppeteer')):
                env['NODE_PATH'] = cand; break
    return env


def probe(scene, total, step, out_json, project=None, timeout=900):
    scene = os.path.abspath(scene.split('?')[0]) + (('?' + scene.split('?', 1)[1]) if '?' in scene else '')
    project = project or os.path.dirname(os.path.dirname(scene.split('?')[0]))
    js = os.path.join(project, 'out', '.overflow_probe.js')
    os.makedirs(os.path.dirname(js), exist_ok=True)
    if not os.path.exists(js) or open(js, encoding='utf-8').read() != PROBE_JS:
        open(js, 'w', encoding='utf-8').write(PROBE_JS)
    r = subprocess.run(['node', js, scene, '%.3f' % total, '%.3f' % step, out_json], capture_output=True, text=True, env=_node_env(project), cwd=project, timeout=timeout)
    if r.returncode != 0:
        raise RuntimeError('overflow probe failed (%d): %s' % (r.returncode, (r.stderr or r.stdout).strip()[-400:]))
    return json.load(open(out_json, encoding='utf-8'))


def run(ctx):
    project = ctx.get('project') or '.'
    cfg = _cfg(ctx.get('qa'))
    scene = ctx.get('scene_html')
    if not scene or not os.path.exists(scene.split('?')[0]):
        return [('text overflow', True, 'no scene html (skipped)')]
    total = float((ctx.get('timeline') or {}).get('total') or ctx.get('dur') or 0)
    if total <= 0:
        return [('text overflow', True, 'no film length known (skipped)')]
    out = os.path.join(project, 'out', 'qa', 'overflow.json')
    try:
        doc = probe(scene, total, float(cfg['step']), out, project)
    except (RuntimeError, OSError, subprocess.TimeoutExpired, ValueError) as e:
        return [('text overflow', False, 'probe unavailable: %s' % str(e)[:160])]
    bad = judge(doc['samples'], cfg)
    doc['offenders'] = [{'t': t, 'id': i, 'text': tx, 'box': b, 'dx': dx, 'dy': dy} for t, i, tx, b, dx, dy in bad]
    json.dump(doc, open(out, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
    if doc.get('errors'):
        return [('text overflow', False, 'page errors: ' + doc['errors'][0][:120])]
    det = ' | '.join('%.0f s %s "%s" box %s +%dx+%d px' % (t, i, tx[:24], b, dx, dy) for t, i, tx, b, dx, dy in bad[:4])
    return [('text overflow', not bad, det[:400] if bad else '%d samples every %.0f s, no text box overflows by > %g px' % (len(doc['samples']), cfg['step'], cfg['px']))]


# ---------------------------------------------------------------- selftest
def selftest(chrome=False):
    ok = True

    def t(cond, msg):
        nonlocal ok
        print('  %s  %s' % ('PASS' if cond else 'FAIL', msg)); ok = ok and bool(cond)
    S = [{'t': 0.0, 'W': 1280, 'H': 720, 'rows': [
        {'id': 'cap', 'tag': 'div', 'cls': 'pill', 'text': 'a caption that wraps', 'box': [300, 600, 680, 40], 'dx': 0, 'dy': 22, 'font': 22},
        {'id': 'kicker', 'tag': 'div', 'cls': 'label', 'text': 'EVERY MONDAY', 'box': [80, 60, 120, 20], 'dx': 9, 'dy': 0, 'font': 16},
        {'id': 'h1', 'tag': 'h1', 'cls': '', 'text': 'Monday, answered.', 'box': [80, 200, 900, 70], 'dx': 0, 'dy': 7, 'font': 64},
        {'id': 'h1b', 'tag': 'h1', 'cls': '', 'text': 'Two lines that lost one', 'box': [80, 300, 900, 70], 'dx': 0, 'dy': 60, 'font': 64},
        {'id': 'kw', 'tag': 'span', 'cls': 'kw', 'text': 'Monday', 'box': [460, 597, 119, 32], 'dx': 0, 'dy': 5, 'font': 22},
        {'id': 'nodeA', 'tag': 'div', 'cls': 'node-label', 'text': 'Agent', 'box': [500, 400, 40, 18], 'dx': 20, 'dy': 0, 'font': 14},
        {'id': 'stage', 'tag': 'div', 'cls': '', 'text': 'x', 'box': [0, 0, 1280, 720], 'dx': 300, 'dy': 0, 'font': 16},
        {'id': 'fine', 'tag': 'p', 'cls': '', 'text': 'fits', 'box': [80, 500, 300, 30], 'dx': 2, 'dy': 3, 'font': 18},
        {'id': 'okd', 'tag': 'div', 'cls': '', 'ok': True, 'text': 'declared', 'box': [80, 540, 100, 20], 'dx': 30, 'dy': 0, 'font': 14}]},
        {'t': 1.0, 'W': 1280, 'H': 720, 'rows': [{'id': 'cap', 'tag': 'div', 'cls': 'pill', 'text': 'a caption that wraps', 'box': [300, 600, 680, 40], 'dx': 0, 'dy': 22, 'font': 22}]}]
    bad = judge(S)
    ids = [b[1] for b in bad]
    t(ids == ['cap', 'kicker', 'h1b'], 'judge: the wrapped caption, the clipped kicker and the lost headline line fail (%s)' % ids)
    t('h1' not in ids and 'kw' not in ids and 'nodeA' not in ids and 'stage' not in ids and 'fine' not in ids and 'okd' not in ids, 'judge: line-height rounding (64 px headline, 22 px karaoke word), icon-node label, the stage, ≤ 3 px and data-overflow-ok are excluded')
    t(len([b for b in bad if b[1] == 'cap']) == 1, 'judge: the same offender at two seconds is reported once')
    if chrome:
        d = tempfile.mkdtemp(prefix='overflow_')
        os.makedirs(os.path.join(d, 'scenes')); os.makedirs(os.path.join(d, 'out'))
        scene = os.path.join(d, 'scenes', 'film.html')
        open(scene, 'w', encoding='utf-8').write(
            '<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;width:1280px;height:720px;background:#082A34;color:#fff;font:22px Arial}'
            '#stage{position:absolute;inset:0}#pill{position:absolute;left:300px;top:600px;width:200px;height:40px;overflow:hidden;white-space:nowrap}'
            '#fit{position:absolute;left:80px;top:100px;width:600px;height:40px;overflow:hidden;white-space:nowrap}#late{position:absolute;left:80px;top:300px;width:120px;height:30px;overflow:hidden;white-space:nowrap;display:none}'
            '</style></head><body><div id="stage"><div id="fit">short line</div><div id="pill">a caption far too long for its pill to hold</div><div id="late">appears at two seconds and overflows</div></div>'
            '<script>window.__seek=function(t){document.getElementById("late").style.display=t>=2?"block":"none";return Promise.resolve()};window.__total=3;</script></body></html>')
        try:
            doc = probe(scene, 3.0, 1.0, os.path.join(d, 'out', 'overflow.json'), d)
            bad = judge(doc['samples'])
            ids = sorted(set(b[1] for b in bad))
            t(len(doc['samples']) == 4 and ids == ['late', 'pill'] and min(b[0] for b in bad if b[1] == 'late') == 2.0, 'chrome: 4 seeks; #pill overflows throughout, #late only from t = 2 s (%s)' % ids)
        except Exception as e:
            t(False, 'chrome probe: %s' % str(e)[:200])
        import shutil
        shutil.rmtree(d, ignore_errors=True)
    print('overflow_gate selftest %s' % ('PASS' if ok else 'FAIL'))
    return 0 if ok else 1


if __name__ == '__main__':
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    a = [x for x in sys.argv[1:] if not x.startswith('--')]
    if '--selftest' in sys.argv or not a:
        sys.exit(selftest(chrome='--chrome' in sys.argv))
    scene = a[0]
    proj = os.path.dirname(os.path.dirname(os.path.abspath(scene.split('?')[0])))
    total = float(sys.argv[sys.argv.index('--total') + 1]) if '--total' in sys.argv else float(json.load(open(os.path.join(proj, 'out', 'timeline.json'), encoding='utf-8')).get('total', 10))
    step = float(sys.argv[sys.argv.index('--step') + 1]) if '--step' in sys.argv else 1.0
    qa = json.load(open(os.path.join(proj, 'qa.json'), encoding='utf-8')) if os.path.exists(os.path.join(proj, 'qa.json')) else {}
    qa.setdefault('overflow', {})['step'] = step
    res = run({'project': proj, 'scene_html': scene, 'timeline': {'total': total}, 'qa': qa})
    for name, ok, d in res:
        print('  %-18s %s  %s' % (name, 'PASS' if ok else 'FAIL', d))
    if '--json' in sys.argv:
        print(open(os.path.join(proj, 'out', 'qa', 'overflow.json'), encoding='utf-8').read()[:4000])
    sys.exit(0 if all(ok for _, ok, _ in res) else 1)
