# -*- coding: utf-8 -*-
"""snapshot.py — golden frames per shot, a contact sheet, and a diff against the previous run.

    python gates/snapshot.py scenes/film.html [--at 3.0,12.8] [--out out/snapshots] [--golden golden]
                             [--update] [--max-changed 1.0] [--psnr 40] [--png] [--json] [--selftest]

Reviewers read a film from stills before they watch it. One capture per shot makes a rebuild reviewable in a
single image, and a diff against the previous run says exactly which shot a narration change moved.

Times (default) — one label per capture:
  title      FILM.openEnd / 2                       the recreated title card
  <clip>     shot.t0 + 1.0 s                        each shot, one second in (establishing push under way)
  close      FILM.close + 0.5                       the closing card
  tail       END - max(0.05 s, 3 % of END)          the readable tail: seeking to the exact end renders blank
Shots and FILM come from scenes/shots.js via node (same loading as export_timeline.js); without node the cuts
in out/timeline.json are used (cut + 1.0). `--at` adds explicit times (the tail is appended unless a time is
within 0.05 s of it).

Captures are cold seeks through the canary probe (fonts.ready, decode-aware), saved as 960x540 JPEG q85 so a
golden set stays small in a public repo (`--png` keeps lossless 1280x720). out/snapshots/contact.jpg tiles
every capture with its label (cols = min(4, ceil(sqrt(n)))).

Compare: when golden/ exists each capture is compared with golden/<label>.jpg: changed-pixel % (|gray delta|
> 24, the metric qa_film.py uses) and PSNR. A shot PASSES when changed <= --max-changed (default 1.0 %) or
PSNR >= --psnr (default 40 dB). Changed shots go into out/snapshots/diff.jpg as rows golden | current | |delta| x 8.
`--update` promotes the current captures to golden/ (do this after a reviewed, intentional change).

QA gate: GATE_NAMES = ['golden']; runs only when golden/ exists (otherwise PASS with an info detail).
qa.json: {"snapshot": {"golden": "golden", "max_changed": 1.0, "psnr": 40}}.
"""
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import canary as CAN  # noqa: E402  (the shared puppeteer probe + compare)

GATE_NAMES = ['golden']
GOLDEN_W, GOLDEN_H, GOLDEN_Q = 960, 540, 85
MAX_CHANGED_PCT = 1.0
PSNR_PASS = 40.0
TAIL_MIN, TAIL_FRAC = 0.05, 0.03
NEAR_TAIL = 0.05

SHOTS_JS = r'''/* dump FILM + SHOTS as JSON (generated by gates/snapshot.py) */
const path = require('path');
const [timing, shots, lib] = process.argv.slice(2);
global.window = global;
require(path.resolve(lib, 'grammar.js'));
global.TX = require(path.resolve(lib, 'timeline.js')).load(timing);
require(path.resolve(lib, 'footage.js'));
require(path.resolve(shots));
const F = global.FILM || {}, SH = global.SHOTS || [];
process.stdout.write(JSON.stringify({ total: TX.total, openEnd: F.openEnd, close: F.close,
  shots: SH.map(s => ({ t0: s.t0, t1: s.t1, clip: s.clip, seam: !!s.seam, establish: s.establish || null })) }));
'''


def load_shots(project, name='film'):
    """{total, openEnd, close, shots:[{t0,t1,clip,...}]} via node; None when the timing/shots files are missing."""
    timing = os.path.join(project, 'scenes', 'timing_%s_data.js' % name)
    shots = os.path.join(project, 'scenes', 'shots.js')
    lib = os.path.join(project, 'scenes', 'lib')
    if not (os.path.exists(timing) and os.path.exists(shots) and os.path.isdir(lib)):
        return None
    fd, tmp = tempfile.mkstemp(suffix='.js', prefix='shots_dump_', dir=os.path.join(project, 'out') if os.path.isdir(os.path.join(project, 'out')) else None)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as f:
            f.write(SHOTS_JS)
        r = subprocess.run(['node', tmp, timing, shots, lib], capture_output=True, text=True, timeout=30, cwd=project)
        return json.loads(r.stdout) if r.returncode == 0 and r.stdout.strip() else None
    except (OSError, ValueError, subprocess.TimeoutExpired):
        return None
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass


def plan_times(project, name='film', at=(), total=None, fps=30):
    """[(label, t)] — title, each shot + 1 s, close, explicit --at times, and the readable tail."""
    info = load_shots(project, name)
    plan = []
    if info:
        total = total or float(info['total'])
        if info.get('openEnd'):
            plan.append(('title', info['openEnd'] / 2.0))
        seen = {}
        for s in info['shots']:
            lab = s['clip'] or 'shot'
            seen[lab] = seen.get(lab, 0) + 1
            plan.append((lab if seen[lab] == 1 else '%s_%d' % (lab, seen[lab]), s['t0'] + 1.0))
        if info.get('close') is not None:
            plan.append(('close', info['close'] + 0.5))
    else:
        tl = os.path.join(project, 'out', 'timeline.json')
        if os.path.exists(tl):
            T = json.load(open(tl, encoding='utf-8'))
            total = total or float(T['total'])
            plan.append(('title', 0.5))
            for i, c in enumerate(T.get('cuts', [])):
                plan.append(('cut%d' % (i + 1), c + 1.0))
    total = total or 10.0
    for i, t in enumerate(at):
        plan.append(('at%d' % (i + 1), float(t)))
    tail = total - max(TAIL_MIN, TAIL_FRAC * total)
    if not any(abs(t - tail) < NEAR_TAIL for _, t in plan):
        plan.append(('tail', tail))
    out, labels = [], set()
    for lab, t in plan:
        if t is None or not (0 <= t <= total + 1.2) or lab in labels:
            continue
        labels.add(lab)
        out.append((lab, CAN.snap(t, fps)))
    return out, total


def _label(im, text):
    from PIL import ImageDraw, ImageFont
    d = ImageDraw.Draw(im)
    try:
        f = ImageFont.truetype('arial.ttf', 18)
    except Exception:
        f = ImageFont.load_default()
    d.rectangle([0, 0, 8 + 10 * len(text), 28], fill=(8, 42, 52))
    d.text((6, 4), text, fill=(233, 243, 249), font=f)
    return im


def capture(scene, plan, out_dir, png=False, project=None, fps=30):
    """Capture every planned time (cold seeks). Returns {label: path}."""
    from PIL import Image
    os.makedirs(out_dir, exist_ok=True)
    times = [t for _, t in plan]
    files, meta = CAN.probe(scene, times, 'cold', os.path.join(out_dir, '_raw'), prefix='s_', fps=fps, png=True, project=project)
    out = {}
    for lab, t in plan:
        src = files['%.3f' % t]
        dst = os.path.join(out_dir, '%s.%s' % (lab, 'png' if png else 'jpg'))
        with Image.open(src) as im:
            im = im.convert('RGB')
            if not png:
                im = im.resize((GOLDEN_W, GOLDEN_H), Image.LANCZOS)
                im.save(dst, quality=GOLDEN_Q, optimize=True)
            else:
                im.save(dst)
        out[lab] = dst
    shutil.rmtree(os.path.join(out_dir, '_raw'), ignore_errors=True)
    return out, meta


def contact_sheet(files, plan, path):
    from PIL import Image
    n = len(plan)
    if not n:
        return None
    cols = min(4, int(math.ceil(math.sqrt(n)))); rows = int(math.ceil(n / cols))
    tw, th = 480, 270
    sheet = Image.new('RGB', (cols * tw, rows * th), (5, 22, 28))
    for i, (lab, t) in enumerate(plan):
        with Image.open(files[lab]) as im:
            tile = _label(im.convert('RGB').resize((tw, th), Image.LANCZOS), '%s  t=%.2f' % (lab, t))
        sheet.paste(tile, ((i % cols) * tw, (i // cols) * th))
    sheet.save(path, quality=88)
    return path


def compare_set(files, golden_dir, max_changed=MAX_CHANGED_PCT, psnr_pass=PSNR_PASS, diff_path=None):
    """Per-label comparison with golden/<label>.<ext>. Returns {ok, rows:[{label, status, changed_pct, psnr}], missing}."""
    import numpy as np
    from PIL import Image
    rows, bad_tiles, missing = [], [], []
    for lab, cur in files.items():
        ext = os.path.splitext(cur)[1]
        g = os.path.join(golden_dir, lab + ext)
        if not os.path.exists(g):
            missing.append(lab); rows.append({'label': lab, 'status': 'new'}); continue
        c = CAN.compare(g, cur)
        ok = c['identical'] or c['changed_pct'] <= max_changed or c['psnr'] >= psnr_pass
        rows.append({'label': lab, 'status': 'same' if c['identical'] else ('ok' if ok else 'CHANGED'), 'changed_pct': c['changed_pct'], 'psnr': c['psnr']})
        if not ok:
            A = np.asarray(Image.open(g).convert('RGB'), dtype=np.int16); B = np.asarray(Image.open(cur).convert('RGB'), dtype=np.int16)
            if A.shape == B.shape:
                D = Image.fromarray(np.clip(np.abs(A - B) * CAN.DIFF_GAIN, 0, 255).astype(np.uint8))
                bad_tiles.append((lab, Image.fromarray(A.astype(np.uint8)), Image.fromarray(B.astype(np.uint8)), D, c))
    if bad_tiles and diff_path:
        tw, th = 480, 270
        sheet = Image.new('RGB', (3 * tw, th * len(bad_tiles)), (5, 22, 28))
        for r, (lab, A, B, D, c) in enumerate(bad_tiles):
            for k, (im, txt) in enumerate(((A, lab + '  golden'), (B, lab + '  current'), (D, '|delta| x8  %.2f%%  %s dB' % (c['changed_pct'], c['psnr'])))):
                sheet.paste(_label(im.resize((tw, th), Image.LANCZOS), txt), (k * tw, r * th))
        sheet.save(diff_path, quality=88)
    changed = [r['label'] for r in rows if r['status'] == 'CHANGED']
    return {'ok': not changed, 'rows': rows, 'changed': changed, 'missing': missing, 'diff': diff_path if bad_tiles else None}


def promote(files, golden_dir):
    os.makedirs(golden_dir, exist_ok=True)
    for lab, cur in files.items():
        shutil.copy2(cur, os.path.join(golden_dir, os.path.basename(cur)))
    return len(files)


def snapshot(scene, project=None, name='film', at=(), out_dir=None, golden_dir=None, update=False, png=False,
             max_changed=MAX_CHANGED_PCT, psnr_pass=PSNR_PASS, fps=30, total=None):
    scene = os.path.abspath(scene)
    project = project or os.path.dirname(os.path.dirname(scene))
    out_dir = out_dir or os.path.join(project, 'out', 'snapshots')
    golden_dir = golden_dir or os.path.join(project, 'golden')
    plan, total = plan_times(project, name, at, total, fps)
    files, meta = capture(scene, plan, out_dir, png=png, project=project, fps=fps)
    sheet = contact_sheet(files, plan, os.path.join(out_dir, 'contact.jpg'))
    rep = {'ok': True, 'plan': plan, 'files': files, 'contact': sheet, 'chrome': meta.get('chrome'), 'errors': meta.get('errors', []), 'golden': golden_dir}
    if os.path.isdir(golden_dir) and os.listdir(golden_dir):
        cmp = compare_set(files, golden_dir, max_changed, psnr_pass, os.path.join(out_dir, 'diff.jpg'))
        rep.update(compare=cmp, ok=cmp['ok'] and not rep['errors'])
    else:
        rep['compare'] = None
    if update:
        rep['promoted'] = promote(files, golden_dir)
    json.dump(rep, open(os.path.join(out_dir, 'snapshots.json'), 'w', encoding='utf-8'), indent=1, default=str)
    return rep


# ------------------------------------------------------------------------------------------------ QA gate
def run(ctx):
    q = (ctx.get('qa') or {}).get('snapshot', {}) or {}
    project = ctx.get('project') or '.'
    golden = os.path.join(project, q.get('golden', 'golden'))
    if not (os.path.isdir(golden) and os.listdir(golden)):
        return [('golden', True, 'no golden/ yet (info) — python gates/snapshot.py scenes/film.html --update after review')]
    rep = snapshot(ctx['scene_html'], project=project, name=(ctx.get('cfg') or {}).get('name', 'film'), golden_dir=golden,
                   max_changed=float(q.get('max_changed', MAX_CHANGED_PCT)), psnr_pass=float(q.get('psnr', PSNR_PASS)),
                   fps=int(ctx.get('fps', 30)), total=float((ctx.get('timeline') or {}).get('total', 0)) or None)
    c = rep['compare'] or {}
    if rep['errors']:
        return [('golden', False, 'page errors: ' + rep['errors'][0][:100])]
    if c.get('changed'):
        worst = max((r for r in c['rows'] if r['status'] == 'CHANGED'), key=lambda r: r['changed_pct'])
        return [('golden', False, 'changed: %s (worst %s %.2f%% / %s dB) -> %s' % (', '.join(c['changed'][:4]), worst['label'], worst['changed_pct'], worst['psnr'], c.get('diff')))]
    return [('golden', True, '%d shots match golden/%s' % (len(c.get('rows', [])), (' (+%d new)' % len(c['missing'])) if c.get('missing') else ''))]


# ------------------------------------------------------------------------------------------------ selftest
def selftest():
    d = tempfile.mkdtemp(prefix='snapshot_selftest_')
    os.makedirs(os.path.join(d, 'scenes')); os.makedirs(os.path.join(d, 'out'))
    scene = os.path.join(d, 'scenes', 'film.html')
    open(scene, 'w', encoding='utf-8').write(CAN._SCENE % CAN.GOOD_VALUE)
    json.dump({'total': 6.0, 'cuts': [2.0, 4.0]}, open(os.path.join(d, 'out', 'timeline.json'), 'w'))
    r1 = snapshot(scene, project=d, update=True)
    print('selftest  plan %s' % [(l, t) for l, t in r1['plan']])
    print('selftest  captured %d, promoted %d, contact %s' % (len(r1['files']), r1.get('promoted'), os.path.exists(r1['contact'])))
    r2 = snapshot(scene, project=d)
    same = r2['compare'] and all(r['status'] in ('same', 'ok') for r in r2['compare']['rows'])
    print('selftest  rerun vs golden: %s' % [(r['label'], r['status']) for r in r2['compare']['rows']])
    open(scene, 'w', encoding='utf-8').write((CAN._SCENE % CAN.GOOD_VALUE).replace('#E56B5E', '#2A9D8F').replace('t * 80', 't * 200'))
    r3 = snapshot(scene, project=d)
    changed = r3['compare']['changed']
    print('selftest  edited scene vs golden: changed %s diff %s' % (changed, os.path.basename(r3['compare']['diff'] or '')))
    ok = bool(r1.get('promoted')) and same and bool(changed) and r3['compare']['diff'] and os.path.exists(r3['compare']['diff'])
    shutil.rmtree(d, ignore_errors=True)
    print('selftest  ' + ('PASS' if ok else 'FAIL'))
    return bool(ok)


def main(argv):
    if '--selftest' in argv:
        return 0 if selftest() else 1
    args = [a for a in argv if not a.startswith('--')]
    def opt(name, default=None):
        if name in argv and argv.index(name) + 1 < len(argv):
            v = argv[argv.index(name) + 1]
            if v in args:
                args.remove(v)
            return v
        return default
    at = [float(x) for x in (opt('--at', '') or '').split(',') if x.strip()]
    out = opt('--out'); golden = opt('--golden'); mc = float(opt('--max-changed', MAX_CHANGED_PCT)); ps = float(opt('--psnr', PSNR_PASS))
    name = opt('--name', 'film')
    if not args:
        print(__doc__.split('\n\n')[0]); return 2
    rep = snapshot(args[0], at=at, out_dir=out, golden_dir=golden, update='--update' in argv, png='--png' in argv, max_changed=mc, psnr_pass=ps, name=name)
    if '--json' in argv:
        print(json.dumps(rep, indent=1, default=str)); return 0 if rep['ok'] else 1
    for lab, t in rep['plan']:
        row = next((r for r in (rep['compare'] or {}).get('rows', []) if r['label'] == lab), None)
        st = '' if not row else ('  %-7s %s' % (row['status'], ('%.2f%%  %s dB' % (row['changed_pct'], row['psnr'])) if 'changed_pct' in row else ''))
        print('  %-10s t=%6.2f  %s%s' % (lab, t, os.path.relpath(rep['files'][lab]), st))
    print('contact sheet  %s' % os.path.relpath(rep['contact']))
    if rep['compare'] and rep['compare']['diff']:
        print('diff sheet     %s' % os.path.relpath(rep['compare']['diff']))
    if rep.get('promoted'):
        print('promoted %d captures to %s' % (rep['promoted'], os.path.relpath(rep['golden'])))
    elif rep['compare'] is None:
        print('no golden/ — review the contact sheet, then re-run with --update to freeze these as golden')
    for e in rep['errors']:
        print('  ' + e)
    print('golden ' + ('PASS' if rep['ok'] else 'FAIL'))
    return 0 if rep['ok'] else 1


if __name__ == '__main__':
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.exit(main(sys.argv[1:]))
